name: Run Tests & Linting

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Run Vitest & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e  # v2

      - name: Install Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Vitest
        run: npm run test
